In [1]:
import os
import pandas as pd

In [2]:
excel_file_path = 'C:/Users/ASUS/OneDrive/Documents/中信兄弟/Season_data/2024_non_trackman.xlsx'
sheet_name = 'Sheet1'

In [3]:
data = pd.read_excel(excel_file_path, sheet_name=sheet_name)

In [4]:
data

,LocalDateTime,id,gameId,stadium,umpireInChief,date,eType,awayScores,homeScores,inning,...,trackMan,aimotion,system,bName,pName,cName,fbName,sbName,tbName,SP
0,'2024-03-30T17:07:23.6810+08:00,66081466133ed988f9c51ecb,6607d24cdf5ba4d17362f7ee,臺北大巨蛋 Taipei Dome,張展榮,2024-03-30T08:49:00.000Z,P,0,0,1,...,NaN,NaN,NaN,陳晨威,徐若熙,蔣少宏,NaN,NaN,NaN,True
1,'2024-03-30T17:07:49.7300+08:00,660814a9133ed988f9c51ecc,6607d24cdf5ba4d17362f7ee,臺北大巨蛋 Taipei Dome,張展榮,2024-03-30T08:49:00.000Z,P,0,0,1,...,NaN,NaN,NaN,陳晨威,徐若熙,蔣少宏,NaN,NaN,NaN,True
2,'2024-03-30T17:08:29.5410+08:00,660814f4133ed988f9c51ecd,6607d24cdf5ba4d17362f7ee,臺北大巨蛋 Taipei Dome,張展榮,2024-03-30T08:49:00.000Z,P,0,0,1,...,NaN,NaN,NaN,林立,徐若熙,蔣少宏,NaN,NaN,NaN,True
3,'2024-03-30T17:08:50.8020+08:00,66081508133ed988f9c51ece,6607d24cdf5ba4d17362f7ee,臺北大巨蛋 Taipei Dome,張展榮,2024-03-30T08:49:00.000Z,P,0,0,1,...,NaN,NaN,NaN,林立,徐若熙,蔣少宏,NaN,NaN,NaN,True
4,'2024-03-30T17:09:05.9180+08:00,6608151c133ed988f9c51ecf,6607d24cdf5ba4d17362f7ee,臺北大巨蛋 Taipei Dome,張展榮,2024-03-30T08:49:00.000Z,P,0,0,1,...,NaN,NaN,NaN,林立,徐若熙,蔣少宏,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72324,'2024-05-21T23:46:43.7700+08:00,66508a32b54b053fd9e87156,66508a30b54b053fd9e87151,臺北市立天母棒球場 Tianmu Baseball Stadium,彭楚雲,2024-05-17T10:35:00.000Z,P,1,8,9,...,"{""PitchNo"":""245"",""Date"":""2024/5/17"",""Time"":""19...",NaN,TrackMan,張進德,陳冠偉,吉力吉撈．鞏冠,NaN,NaN,NaN,False
72325,'2024-05-21T23:47:01.8200+08:00,66508a32b54b053fd9e87155,66508a30b54b053fd9e87151,臺北市立天母棒球場 Tianmu Baseball Stadium,彭楚雲,2024-05-17T10:35:00.000Z,P,1,8,9,...,"{""PitchNo"":""246"",""Date"":""2024/5/17"",""Time"":""20...",NaN,TrackMan,張進德,陳冠偉,吉力吉撈．鞏冠,NaN,NaN,NaN,False
72326,'2024-05-21T23:47:26.0120+08:00,66508a32b54b053fd9e87154,66508a30b54b053fd9e87151,臺北市立天母棒球場 Tianmu Baseball Stadium,彭楚雲,2024-05-17T10:35:00.000Z,P,1,8,9,...,"{""PitchNo"":""247"",""Date"":""2024/5/17"",""Time"":""20...",NaN,TrackMan,張進德,陳冠偉,吉力吉撈．鞏冠,NaN,NaN,NaN,False
72327,'2024-05-21T23:48:15.5250+08:00,66508a32b54b053fd9e87153,66508a30b54b053fd9e87151,臺北市立天母棒球場 Tianmu Baseball Stadium,彭楚雲,2024-05-17T10:35:00.000Z,P,1,8,9,...,"{""PitchNo"":""248"",""Date"":""2024/5/17"",""Time"":""21...",NaN,TrackMan,董子恩,陳冠偉,吉力吉撈．鞏冠,張進德,NaN,NaN,False
72328,'2024-05-21T23:48:31.8160+08:00,66508a32b54b053fd9e87152,66508a30b54b053fd9e87151,臺北市立天母棒球場 Tianmu Baseball Stadium,彭楚雲,2024-05-17T10:35:00.000Z,P,1,8,9,...,"{""PitchNo"":""249"",""Date"":""2024/5/17"",""Time"":""21...",NaN,TrackMan,董子恩,陳冠偉,吉力吉撈．鞏冠,張進德,NaN,NaN,False

In [5]:
col = ['umpireInChief','bHand','side','inning','coordX','coordY','pType','call','result']

In [6]:
df = data[col]

In [7]:
name_mapping = {
    'FF':'直球', 
    'CH':'變速球', 
    'FC':'卡特球', 
    'CU':'曲球', 
    'FO':'指叉球',
    'SL':'滑球', 
    'SI':'伸卡球',
    'KN':'彈指曲球', 
    'EP':'小便球'
}

# 新增一列"球員"，根据"Pitcher"列的值匹配中文名
df['球種'] = df['pType'].map(name_mapping)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_11936\2745578358.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['球種'] = df['pType'].map(name_mapping)

In [8]:
df

      umpireInChief bHand  side  inning  coordX  coordY pType call result   球種
0               張展榮     L  AWAY       1   86.11  -81.94    FF    B    NaN   直球
1               張展榮     L  AWAY       1   52.78   51.39    FF    H     GO   直球
2               張展榮     R  AWAY       1   50.00   45.83    FF    F    NaN   直球
3               張展榮     R  AWAY       1    2.78  -12.50    SL   SW    NaN   滑球
4               張展榮     R  AWAY       1  -52.78 -118.06    SL    B    NaN   滑球
...             ...   ...   ...     ...     ...     ...   ...  ...    ...  ...
72324           彭楚雲     L  AWAY       9   22.26   -9.19    FF   FT    NaN   直球
72325           彭楚雲     L  AWAY       9  -42.54  -57.26    FO   SW    NaN  指叉球
72326           彭楚雲     L  AWAY       9   -3.69  -21.03    FO    H     1B  指叉球
72327           彭楚雲     R  AWAY       9  -27.78   35.48    FF    S    NaN   直球
72328           彭楚雲     R  AWAY       9   54.50   -2.53    FF    H   GIDP   直球

[72329 rows x 10 columns]

In [12]:
summary = df.groupby(['umpireInChief', 'result']).size().unstack(fill_value=0)
summary['Total'] =summary.iloc[:, 1:].sum(axis=1)
summary

result,1B,2B,3B,D3S,DP,E,FC,FO,GIDP,GO,...,HR,IBB,ID,IGNORE,IH,SF,SH,SO,uBB,Total
umpireInChief,,,,,,,,,,,,,,,,,,,,,
劉世偉,57,11,2,0,1,1,10,50,5,40,...,7,0,0,0,0,2,0,39,18,188
吳家維,199,57,6,1,0,16,43,310,25,172,...,18,4,0,5,0,14,19,194,103,1004
尤志欽,274,54,6,0,3,21,45,361,26,227,...,18,4,0,5,0,10,21,261,99,1181
張展榮,188,46,7,3,1,14,35,284,26,218,...,16,3,0,0,0,13,14,192,101,986
彭楚雲,213,33,6,1,5,16,29,300,33,198,...,15,3,0,3,0,13,24,214,100,1009
林金達,296,66,12,1,2,21,49,402,22,294,...,18,2,0,4,0,19,21,293,116,1361
楊崇煇,197,40,6,2,8,16,29,298,23,226,...,13,4,0,0,0,6,12,232,99,1027
江春緯,244,52,5,4,1,17,39,345,39,255,...,23,4,1,1,0,12,22,234,95,1169
王俊宏,211,47,6,4,4,11,30,228,31,179,...,16,1,0,4,0,13,8,196,74,860
紀華文,256,56,3,6,3,17,38,334,33,210,...,17,5,1,0,0,17,29,240,117,1150
羅鈞鴻,273,40,6,2,4,13,52,315,27,258,...,21,1,0,3,1,12,22,306,132,1234
范元淦,157,29,8,1,0,6,41,225,20,153,...,14,1,0,0,0,5,14,139,84,750
蔡豐澤,202,52,10,2,2,11,41,316,20,219,...,16,3,0,2,0,10,14,186,96,1015
邱景彥,255,73,6,3,3,13,45,391,29,276,...,17,1,0,1,0,13,26,230,114,1257
陳均瑋,284,56,5,0,3,18,43,341,36,246,...,19,1,0,6,0,12,19,248,134,1201

In [13]:
summary.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15 entries, 劉世偉 to 陳均瑋
Data columns (total 21 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1B      15 non-null     int64
 1   2B      15 non-null     int64
 2   3B      15 non-null     int64
 3   D3S     15 non-null     int64
 4   DP      15 non-null     int64
 5   E       15 non-null     int64
 6   FC      15 non-null     int64
 7   FO      15 non-null     int64
 8   GIDP    15 non-null     int64
 9   GO      15 non-null     int64
 10  HBP     15 non-null     int64
 11  HR      15 non-null     int64
 12  IBB     15 non-null     int64
 13  ID      15 non-null     int64
 14  IGNORE  15 non-null     int64
 15  IH      15 non-null     int64
 16  SF      15 non-null     int64
 17  SH      15 non-null     int64
 18  SO      15 non-null     int64
 19  uBB     15 non-null     int64
 20  Total   15 non-null     int64
dtypes: int64(21)
memory usage: 2.6+ KB

In [18]:
summary['PA']=summary['Total']-summary['IGNORE']-summary['ID']
summary['BB%']=summary['uBB']/summary['PA']*100
summary['K%']=summary['SO']/summary['PA']*100

In [19]:
summary

result,1B,2B,3B,D3S,DP,E,FC,FO,GIDP,GO,...,IGNORE,IH,SF,SH,SO,uBB,Total,PA,BB%,K%
umpireInChief,,,,,,,,,,,,,,,,,,,,,
劉世偉,57,11,2,0,1,1,10,50,5,40,...,0,0,2,0,39,18,188,188,9.574468,20.744681
吳家維,199,57,6,1,0,16,43,310,25,172,...,5,0,14,19,194,103,1004,999,10.310310,19.419419
尤志欽,274,54,6,0,3,21,45,361,26,227,...,5,0,10,21,261,99,1181,1176,8.418367,22.193878
張展榮,188,46,7,3,1,14,35,284,26,218,...,0,0,13,14,192,101,986,986,10.243408,19.472617
彭楚雲,213,33,6,1,5,16,29,300,33,198,...,3,0,13,24,214,100,1009,1006,9.940358,21.272366
林金達,296,66,12,1,2,21,49,402,22,294,...,4,0,19,21,293,116,1361,1357,8.548268,21.591746
楊崇煇,197,40,6,2,8,16,29,298,23,226,...,0,0,6,12,232,99,1027,1027,9.639727,22.590068
江春緯,244,52,5,4,1,17,39,345,39,255,...,1,0,12,22,234,95,1169,1167,8.140531,20.051414
王俊宏,211,47,6,4,4,11,30,228,31,179,...,4,0,13,8,196,74,860,856,8.644860,22.897196
紀華文,256,56,3,6,3,17,38,334,33,210,...,0,0,17,29,240,117,1150,1149,10.182768,20.887728
羅鈞鴻,273,40,6,2,4,13,52,315,27,258,...,3,1,12,22,306,132,1234,1231,10.722989,24.857839
范元淦,157,29,8,1,0,6,41,225,20,153,...,0,0,5,14,139,84,750,750,11.200000,18.533333
蔡豐澤,202,52,10,2,2,11,41,316,20,219,...,2,0,10,14,186,96,1015,1013,9.476802,18.361303
邱景彥,255,73,6,3,3,13,45,391,29,276,...,1,0,13,26,230,114,1257,1256,9.076433,18.312102
陳均瑋,284,56,5,0,3,18,43,341,36,246,...,6,0,12,19,248,134,1201,1195,11.213389,20.753138